# Generated by Django 5.1.3 on 2024-11-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
